var g = require('../grammar')


/**
 * NOTE: The large sets of preposition substitutions are implemented via a temporary, slapdash design. This implementation will be redesigned later.
 *
 * Below, the substitutions are grouped as separate term sequences, an extra rule below each preposition's base sequence, because otherwise some have introduced the generation of additional ambiguous parse trees. This is related to the flattening in `calcHeuristicCosts` for rules generated by `splitRegexTerminalSymbols`. The in-production successor to that implementation (also in `calcHeuristicCosts`) will be extended to avoid these additional ambiguous parses.
 */

var prepSymNamePrefix = 'prep'

// (people followed) by (me)
exports.agent = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'agent'),
	insertionCost: 0.5,
	acceptedTerms: [ 'by' ],
	substitutedTerms: [
		{ term: 'from', costPenalty: 1 },
		{ term: 'via', costPenalty: 1 },
		{ term: 'of', costPenalty: 0.5 },
		{ costPenalty: 3, term: g.newTermSequence({
			symbolName: g.hyphenate(prepSymNamePrefix, 'agent', 'substitutions'),
			acceptedTerms: [ 'aboard', 'above', 'absent', 'across', 'afore', 'after', 'against', 'along', 'alongside', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'at', 'athwart', 'atop', 'barring', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'between', 'betwixt', 'beyond', 'but', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'for', 'given', 'in', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'next', 'notwithstanding', 'off', 'on', 'onto', 'opposite', 'out', 'outside', 'over', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'to', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'with', 'within', 'without', 'worth' ],
		}) },
	],
})

var prepPossSubstitutions = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'possessor', 'substitutions'),
	acceptedTerms: [ 'aboard', 'above', 'absent', 'across', 'afore', 'after', 'against', 'along', 'alongside', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'athwart', 'atop', 'barring', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'between', 'betwixt', 'beyond', 'but', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'given', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'next', 'notwithstanding', 'off', 'onto', 'opposite', 'out', 'outside', 'over', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'via', 'within', 'without', 'worth' ],
})

// (followers) of (mine)
exports.possessor = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'possessor'),
	insertionCost: 0.5,
	acceptedTerms: [ 'of' ],
	substitutedTerms: [
		{ term: 'with', costPenalty: 1 },
		{ term: 'to', costPenalty: 1 },
		{ term: prepPossSubstitutions, costPenalty: 2 },
	],
})

// (issues) with (`<int>` comments)
exports.possessed = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'possessed'),
	insertionCost: 0.5,
	acceptedTerms: [ 'with' ],
	substitutedTerms: [
		{ term: 'have', costPenalty: 1 },
		{ term: 'having', costPenalty: 1 },
		{ term: 'containing', costPenalty: 1 },
		{ term: prepPossSubstitutions, costPenalty: 2 },
	],
})

// (likers) of (`[repositories+]`)
exports.participant = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'participant'),
	insertionCost: 0.5,
	acceptedTerms: [ 'of' ],
	substitutedTerms: [
		{ term: 'at', costPenalty: 1 },
		{ term: 'for', costPenalty: 1 },
		{ term: 'in', costPenalty: 1 },
		{ term: 'with', costPenalty: 1 },
	],
})

// (contributors) to (`[repositories+]`)
exports.receiver = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'receiver'),
	insertionCost: 0.5,
	acceptedTerms: [ 'to', 'of' ],
})

// (people who work) on (`[repositories+]`)
exports.surface = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'surface'),
	insertionCost: 0.5,
	acceptedTerms: [ 'on' ],
})

// (followers `{user}` shares) with (me)
exports.associative = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'associative'),
	insertionCost: 0.5,
	acceptedTerms: [ 'with' ],
	substitutedTerms: [
		{ term: 'alongside', costPenalty: 1 },
		{ term: 'of', costPenalty: 1 },
		{ term: 'to', costPenalty: 1 },
		{ costPenalty: 3, term: g.newTermSequence({
			symbolName: g.hyphenate(prepSymNamePrefix, 'associative', 'substitutions'),
			acceptedTerms: [ 'aboard', 'above', 'absent', 'across', 'afore', 'after', 'against', 'along', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'at', 'athwart', 'atop', 'barring', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'between', 'betwixt', 'beyond', 'but', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'for', 'from', 'given', 'in', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'next', 'notwithstanding', 'off', 'on', 'onto', 'opposite', 'out', 'outside', 'over', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'via', 'with', 'within', 'without', 'worth' ],
		}) },
	],
})

// (repos written) in ({language})
exports.language = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'language'),
	insertionCost: 0.5,
	acceptedTerms: [ 'in' ],
	substitutedTerms: [
		{ term: 'with', costPenalty: 0.5 },
		{ term: 'using', costPenalty: 0.5 },
	],
})

// (repos created) in (`[year]`)
exports.container = g.newSymbol(prepSymNamePrefix, 'container').addWord({
	insertionCost: 0.5,
	accepted: [ 'in', 'within', 'during' ],
	substitutions: [
		{ symbol: 'on', costPenalty: 0.8 },
		{ symbol: 'from', costPenalty: 0.8 },
		{ symbol: 'of', costPenalty: 1 },
		{ symbol: 'inside |of', costPenalty: 1 },
		{ symbol: 'into', costPenalty: 1 },
		{ symbol: 'aboard|about|above|absent|across|afore|after|against|along|alongside|amid|amidst|among|amongst|around|aside|astride|at|athwart|atop|barring|before|behind|below|beneath|beside|besides|between|betwixt|beyond|but|by|despite|down|except|excluding|failing|following|for|given|including|lest|like|minus|modulo|near|notwithstanding|off|onto|opposite|out|outside|over|pace|past|per|plus|pro|qua|sans|save|since|than|through|thru|throughout|thruout|till|times|to|toward|towards|under|underneath|unlike|until|unto|up|upon|versus|vs|via|with|without|worth', costPenalty: 2 },
	],
})

// (repos created) on ([month] [day] `[year]`)
exports.day = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'day'),
	insertionCost: 0.5,
	acceptedTerms: [ 'on' ],
	substitutedTerms: [
		{ term: 'in', costPenalty: 0.5 },
		{ term: 'within', costPenalty: 0.5 },
		{ term: 'during', costPenalty: 0.5 },
	],
})

// (repos created) before (`[year]`)
exports.before = g.newSymbol(prepSymNamePrefix, 'before').addWord({
	insertionCost: 0.5,
	accepted: [ 'before', 'until', 'earlier than', 'prior|up to', '<' ],
	substitutions: [
		{ symbol: 'aboard|above|absent|across|afore|after|against|along|alongside|amid|amidst|among|amongst|around|aside|astride|athwart|atop|barring|behind|below|beneath|beside|besides|between|betwixt|beyond|but|despite|down|during|except|excluding|failing|following|given|including|inside|into|lest|like|minus|modulo|near|next|notwithstanding|off|onto|opposite|out|outside|over|pace|past|per|plus|pro|qua|sans|save|since|than|through|thru|throughout|thruout|till|times|toward|towards|under|underneath|unlike|unto|up|upon|versus|vs|via|with|within|without|worth', costPenalty: 2 },
	],
})

// (repos created) after (`[year]`)
exports.after = g.newSymbol(prepSymNamePrefix, 'after').addWord({
	insertionCost: 1,
	accepted: [ 'after', 'since', 'later than', 'subsequent to', '>' ],
	substitutions: [
		{ symbol: 'aboard|above|absent|across|afore|against|along|alongside|amid|amidst|among|amongst|around|aside|astride|athwart|atop|barring|before|behind|below|beneath|beside|besides|between|betwixt|beyond|but|despite|down|during|except|excluding|failing|following|given|including|inside|into|lest|like|minus|modulo|near|next|notwithstanding|off|onto|opposite|out|outside|over|pace|past|per|plus|pro|qua|sans|save|than|through|thru|throughout|thruout|till|times|toward|towards|under|underneath|unlike|until|unto|up|upon|versus|vs|via|with|within|without|worth', costPenalty: 2 },
	],
})

var prepIntervalSubstitutions = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'start', 'substitutions'),
	acceptedTerms: [ 'aboard', 'above', 'absent', 'across', 'afore', 'after', 'against', 'along', 'alongside', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'athwart', 'atop', 'barring', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'between', 'betwixt', 'beyond', 'but', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'given', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'next', 'notwithstanding', 'off', 'onto', 'opposite', 'out', 'outside', 'over', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'via', 'with', 'within', 'without', 'worth' ],
})

// (repos created) from (`[year]` to `[year]`)
exports.start = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'start'),
	insertionCost: 0.8,
	acceptedTerms: [ 'from' ],
	substitutedTerms: [
		{ term: 'in', costPenalty: 1 },
		{ term: prepIntervalSubstitutions, costPenalty: 2 },
	],
})

// (repos created from `[year]`) to (`[year]`)
// (issues with `<int>`) to (`<int>` comments)
exports.end = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'end'),
	insertionCost: 0.5,
	acceptedTerms: [ 'to' ],
	substitutedTerms: [
		{ term: prepIntervalSubstitutions, costPenalty: 2 },
	],
})

// (issues with) between (`<int>` and `<int>` comments)
exports.between = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'between'),
	insertionCost: 2,
	acceptedTerms: [ 'between' ],
	substitutedTerms: [
		{ costPenalty: 2, term: g.newTermSequence({
			symbolName: g.hyphenate(prepSymNamePrefix, 'between', 'substitutions'),
			acceptedTerms: [ 'aboard', 'above', 'absent', 'across', 'afore', 'after', 'against', 'along', 'alongside', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'athwart', 'atop', 'barring', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'betwixt', 'beyond', 'but', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'from', 'given', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'next', 'notwithstanding', 'off', 'onto', 'opposite', 'out', 'outside', 'over', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'via', 'with', 'within', 'without', 'worth' ],
		}) },
	],
})

// (issues with) over (`<int>` comments)
exports.over = g.newSymbol(prepSymNamePrefix, 'over').addWord({
	insertionCost: 0.5,
	accepted: [ 'over', 'above', 'beyond', 'greater|more than', '>' ],
}).addRule({
	rhs: [
		g.newTermSequence({
			symbolName: g.hyphenate(prepSymNamePrefix, 'over', 'substitutions'),
			acceptedTerms: [ 'aboard', 'absent', 'across', 'afore', 'after', 'against', 'along', 'alongside', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'athwart', 'atop', 'barring', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'between', 'betwixt', 'but', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'given', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'next', 'notwithstanding', 'off', 'onto', 'opposite', 'out', 'outside', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'via', 'with', 'within', 'without', 'worth' ],
		})
	],
	costPenalty: 2,
	text: 'over',
})

// (issues with) under (`<int>` comments)
exports.under = g.newSymbol(prepSymNamePrefix, 'under').addWord({
	insertionCost: 0.5,
	accepted: [ 'under', 'below', 'fewer|less than', '<' ],
	substitutions: [
		{ symbol: 'aboard|above|absent|across|afore|after|against|along|alongside|amid|amidst|among|amongst|around|aside|astride|athwart|atop|barring|before|behind|beneath|beside|besides|between|betwixt|beyond|but|despite|down|during|except|excluding|failing|following|given|including|inside|into|lest|like|minus|modulo|near|next|notwithstanding|off|onto|opposite|out|outside|over|pace|past|per|plus|pro|qua|sans|save|since|than|through|thru|throughout|thruout|till|times|toward|towards|underneath|unlike|until|unto|up|upon|versus|vs|via|with|within|without|worth', costPenalty: 2 },
	],
})

// (companies that raised `<int>`) in (funding)
exports.medium = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'medium'),
	insertionCost: 0.5,
	acceptedTerms: [ 'in', 'of' ],
})

// The benefactive case expresses the person/thing (i.e., the referent of the noun) that benefits from the action of the verb (or the situation expressed by the clause). E.g., "for", "for the benefit of", and "intended for".
// (people who work) at|for (`[company]`)
exports.benefactive = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'benefactive'),
	insertionCost: 0.5,
	acceptedTerms: [ 'at', 'for' ],
	substitutedTerms: [
		{ costPenalty: 3, term: g.newTermSequence({
			symbolName: g.hyphenate(prepSymNamePrefix, 'benefactive', 'substitutions'),
			acceptedTerms: [ 'aboard', 'above', 'absent', 'across', 'afore', 'after', 'against', 'along', 'alongside', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'athwart', 'atop', 'barring', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'between', 'betwixt', 'beyond', 'but', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'from', 'given', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'next', 'notwithstanding', 'off', 'onto', 'opposite', 'out', 'outside', 'over', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'via', 'with', 'within', 'without', 'worth' ],
		}) },
	],
})

// (followers I and `{user}` have) in (common)
// (followers I have) in (common with `{user}`)
exports.in = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'in'),
	insertionCost: 0.5,
	acceptedTerms: [ 'in' ],
})

// (people who contribute) to (`[repositories+]`)
exports.to = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'to'),
	insertionCost: 0.5,
	acceptedTerms: [ 'to' ],
})