var g = require('../grammar')
var terms = require('./terms')


/**
 * NOTE: The large sets of preposition substituted terms are implemented via a temporary, slapdash design. This implementation will be redesigned later.
 *
 * Below, the substituted terms are grouped as separate term sequences, an extra rule below each preposition's base sequence, because otherwise some have introduced the generation of additional ambiguous parse trees. This is related to the flattening in `calcHeuristicCosts` for rules generated by `splitRegexTerminalSymbols`. The in-production successor to that implementation (also in `calcHeuristicCosts`) will be extended to avoid these additional ambiguous parses.
 */

var prepSymNamePrefix = 'prep'

// (people followed) by (me)
exports.agent = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'agent'),
	insertionCost: 0.5,
	acceptedTerms: [ 'by' ],
	substitutedTerms: [
		{ term: 'from', costPenalty: 1 },
		{ term: 'via', costPenalty: 1 },
		{ term: 'of', costPenalty: 0.5 },
		{ costPenalty: 3, term: g.newTermSequence({
				symbolName: g.hyphenate(prepSymNamePrefix, 'agent', 'substituted', 'prepositions'),
				acceptedTerms: [ 'aboard', 'above', 'absent', 'across', 'afore', 'after', 'against', 'along', 'alongside', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'at', 'athwart', 'atop', 'barring', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'between', 'betwixt', 'beyond', 'but', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'for', 'given', 'in', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'next', 'notwithstanding', 'off', 'on', 'onto', 'opposite', 'out', 'outside', 'over', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'to', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'with', 'within', 'without', 'worth' ],
		}) },
	],
})

var prepPossSubstitutedPreps = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'poss', 'substituted', 'prepositions'),
	acceptedTerms: [ 'aboard', 'above', 'absent', 'across', 'afore', 'after', 'against', 'along', 'alongside', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'athwart', 'atop', 'barring', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'between', 'betwixt', 'beyond', 'but', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'given', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'next', 'notwithstanding', 'off', 'onto', 'opposite', 'out', 'outside', 'over', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'via', 'within', 'without', 'worth' ],
})

// (followers) of (mine)
exports.possessor = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'possessor'),
	insertionCost: 0.5,
	acceptedTerms: [ 'of' ],
	substitutedTerms: [
		{ term: 'with', costPenalty: 1 },
		{ term: 'to', costPenalty: 1 },
		{ term: prepPossSubstitutedPreps, costPenalty: 2 },
	],
})

// (issues) with (`<int>` comments)
exports.possessed = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'possessed'),
	insertionCost: 0.5,
	acceptedTerms: [ 'with' ],
	substitutedTerms: [
		{ term: 'have', costPenalty: 1 },
		{ term: 'having', costPenalty: 1 },
		{ term: 'containing', costPenalty: 1 },
		{ term: prepPossSubstitutedPreps, costPenalty: 2 },
	],
})

var prepInside = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'inside'),
	acceptedTerms: [ 'inside' ],
})

// (repos created) inside of (`[year]`) -> ... in (`[year]`)
exports.of = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'of'),
	insertionCost: 0.5,
	acceptedTerms: [ 'of' ],
})

// (companies) in (`[location]`)
exports.container = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'container'),
	insertionCost: 0.5,
	acceptedTerms: [ 'in', 'within' ],
	substitutedTerms: [
		{ term: 'from', costPenalty: 0.7 },
		{ term: 'of', costPenalty: 1 },
		{ term: 'into', costPenalty: 1 },
		{ term: [ prepInside, exports.of ], costPenalty: 1 },
		{ costPenalty: 2, term: g.newTermSequence({
				symbolName: g.hyphenate(prepSymNamePrefix, 'container', 'substituted', 'prepositions'),
				acceptedTerms: [ 'aboard', 'about', 'above', 'absent', 'across', 'afore', 'after', 'against', 'along', 'alongside', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'at', 'athwart', 'atop', 'barring', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'between', 'betwixt', 'beyond', 'but', 'by', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'for', 'from', 'given', 'in', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'notwithstanding', 'off', 'on', 'onto', 'opposite', 'out', 'outside', 'over', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'to', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'via', 'with', 'within', 'without', 'worth' ],
		}) }
	],
})

// (likers) of (`[repositories+]`)
exports.participant = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'participant'),
	insertionCost: 0.5,
	acceptedTerms: [ 'of' ],
	substitutedTerms: [
		{ term: 'at', costPenalty: 1 },
		{ term: 'for', costPenalty: 1 },
		{ term: 'in', costPenalty: 1 },
		{ term: 'with', costPenalty: 1 },
	],
})

// (investors) in (`[companies+]`)
exports.investor = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'investor'),
	insertionCost: 0.5,
	acceptedTerms: [ 'in' ],
	substitutedTerms: [
		'of',
		{ term: 'for', costPenalty: 1 },
		{ term: 'with', costPenalty: 1 },
	],
})

// (people who contribute) to (`[repositories+]`)
exports.to = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'to'),
	insertionCost: 0.5,
	acceptedTerms: [ 'to' ],
})

// (contributors) to (`[repositories+]`)
exports.receiver = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'receiver'),
	insertionCost: 0.5,
	acceptedTerms: [ 'to', 'of' ],
})

// (people who work) on (`[repositories+]`)
exports.surface = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'surface'),
	insertionCost: 0.5,
	acceptedTerms: [ 'on' ],
})

// (followers `{user}` shares) with (me)
exports.associative = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'associative'),
	insertionCost: 0.5,
	acceptedTerms: [ 'with' ],
	substitutedTerms: [
		{ term: 'alongside', costPenalty: 1 },
		{ term: 'of', costPenalty: 1 },
		{ term: 'to', costPenalty: 1 },
		{ costPenalty: 3, term: g.newTermSequence({
				symbolName: g.hyphenate(prepSymNamePrefix, 'associative', 'substituted', 'prepositions'),
				acceptedTerms: [ 'aboard', 'above', 'absent', 'across', 'afore', 'after', 'against', 'along', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'at', 'athwart', 'atop', 'barring', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'between', 'betwixt', 'beyond', 'but', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'for', 'from', 'given', 'in', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'next', 'notwithstanding', 'off', 'on', 'onto', 'opposite', 'out', 'outside', 'over', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'via', 'with', 'within', 'without', 'worth' ],
		}) },
	],
})

// (repos written) in ({language})
exports.language = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'language'),
	insertionCost: 0.5,
	acceptedTerms: [ 'in' ],
	substitutedTerms: [
		{ term: 'with', costPenalty: 0.5 },
		{ term: 'using', costPenalty: 0.5 },
	],
})

// (repos created) in (`[year]`)
exports.origin = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'origin'),
	// FIXME: Change `insertionCost` to 0.8 after deprecating `splitRegexTerminalSymbols`.
	insertionCost: 0.5,
	acceptedTerms: [ 'in', 'within', 'during' ],
	substitutedTerms: [
		{ term: 'on', costPenalty: 0.8 },
		{ term: 'from', costPenalty: 0.8 },
		{ term: 'of', costPenalty: 1 },
		{ term: [ prepInside, exports.of ], costPenalty: 1 },
		{ costPenalty: 2, term: g.newTermSequence({
				symbolName: g.hyphenate(prepSymNamePrefix, 'origin', 'substituted', 'prepositions'),
				acceptedTerms: [ 'aboard', 'about', 'above', 'absent', 'across', 'afore', 'after', 'against', 'along', 'alongside', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'at', 'athwart', 'atop', 'barring', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'between', 'betwixt', 'beyond', 'but', 'by', 'despite', 'down', 'except', 'excluding', 'failing', 'following', 'for', 'given', 'including', 'lest', 'like', 'minus', 'modulo', 'near', 'notwithstanding', 'off', 'onto', 'opposite', 'out', 'outside', 'over', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'to', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'via', 'with', 'without', 'worth' ],
		}) }
	],
})

// (repos created) on ([month] [day] `[year]`)
exports.day = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'day'),
	insertionCost: 0.5,
	acceptedTerms: [ 'on' ],
	substitutedTerms: [
		{ term: 'in', costPenalty: 0.5 },
		{ term: 'within', costPenalty: 0.5 },
		{ term: 'during', costPenalty: 0.5 },
	],
})

// (repos created earlier|later) than (`[date-value]`)
// (issues with greater|fewer) than (`<int>` comments)
exports.than = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'than'),
	insertionCost: 0.5,
	acceptedTerms: [ 'than' ],
})

// (repos created) before (`[date-value]`)
exports.before = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'before'),
	insertionCost: 0.5,
	acceptedTerms: [
		'before',
		'until',
		// Define these term sets without substitutions, though some are prepositions; otherwise may create ambiguity with the base sequence's substitutions.
		// No insertion costs for neither `[term-earlier]` nor `[term-prior]`.
		[ terms.earlier, exports.than ],
		[ terms.prior, exports.to ],
	],
	substitutedTerms: [
		'<',
		{ costPenalty: 2, term: g.newTermSequence({
				symbolName: g.hyphenate(prepSymNamePrefix, 'before', 'substituted', 'prepositions'),
				acceptedTerms: [ 'aboard', 'above', 'absent', 'across', 'afore', 'after', 'against', 'along', 'alongside', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'athwart', 'atop', 'barring', 'behind', 'below', 'beneath', 'beside', 'besides', 'between', 'betwixt', 'beyond', 'but', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'given', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'next', 'notwithstanding', 'off', 'onto', 'opposite', 'out', 'outside', 'over', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'toward', 'towards', 'under', 'underneath', 'unlike', 'unto', 'up', 'upon', 'versus', 'vs', 'via', 'with', 'within', 'without', 'worth' ],
		}) },
	],
})

// (repos created) after (`[date-value]`)
exports.after = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'after'),
	// Use an insertion cost greater than `[prep-before]` for consistent suggestion ordering.
	insertionCost: 1,
	acceptedTerms: [
		'after',
		'since',
		// Define these term sets without substitutions, though some are prepositions; otherwise may create ambiguity with the base sequence's substitutions.
		// No insertion costs for neither `[term-later]` nor `[term-subsequent]`.
		[ terms.later, exports.than ],
		[ terms.subsequent, exports.to ],
	],
	substitutedTerms: [
		'>',
		{ costPenalty: 2, term: g.newTermSequence({
				symbolName: g.hyphenate(prepSymNamePrefix, 'after', 'substituted', 'prepositions'),
				acceptedTerms: [ 'aboard', 'above', 'absent', 'across', 'afore', 'against', 'along', 'alongside', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'athwart', 'atop', 'barring', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'between', 'betwixt', 'beyond', 'but', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'given', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'next', 'notwithstanding', 'off', 'onto', 'opposite', 'out', 'outside', 'over', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'via', 'with', 'within', 'without', 'worth' ],
		}) },
	],
})

var prepIntervalSubstitutedPreps = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'start', 'substituted', 'prepositions'),
	acceptedTerms: [ 'aboard', 'above', 'absent', 'across', 'afore', 'after', 'against', 'along', 'alongside', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'athwart', 'atop', 'barring', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'between', 'betwixt', 'beyond', 'but', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'given', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'next', 'notwithstanding', 'off', 'onto', 'opposite', 'out', 'outside', 'over', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'via', 'with', 'within', 'without', 'worth' ],
})

// (repos created) from (`[date-value]` to `[date-value]`)
exports.start = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'start'),
	insertionCost: 0.8,
	acceptedTerms: [ 'from' ],
	substitutedTerms: [
		{ term: 'in', costPenalty: 1 },
		{ term: prepIntervalSubstitutedPreps, costPenalty: 2 },
	],
})

// (repos created from `[date-value]`) to (`[date-value]`)
// (issues with `<int>`) to (`<int>` comments)
exports.end = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'end'),
	insertionCost: 0.5,
	acceptedTerms: [ 'to' ],
	substitutedTerms: [
		{ term: prepIntervalSubstitutedPreps, costPenalty: 2 },
	],
})

// (issues with) between (`<int>` and `<int>` comments)
exports.between = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'between'),
	insertionCost: 2,
	acceptedTerms: [ 'between' ],
	substitutedTerms: [
		{ costPenalty: 2, term: g.newTermSequence({
				symbolName: g.hyphenate(prepSymNamePrefix, 'between', 'substituted', 'prepositions'),
				acceptedTerms: [ 'aboard', 'above', 'absent', 'across', 'afore', 'after', 'against', 'along', 'alongside', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'athwart', 'atop', 'barring', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'betwixt', 'beyond', 'but', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'from', 'given', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'next', 'notwithstanding', 'off', 'onto', 'opposite', 'out', 'outside', 'over', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'via', 'with', 'within', 'without', 'worth' ],
		}) },
	],
})

// (issues with) over (`<int>` comments)
exports.over = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'over'),
	insertionCost: 0.5,
	acceptedTerms: [
		'over',
		'above',
		'beyond',
		'>',
		[ terms.greater, exports.than ],
	],
	substitutedTerms: [
		{ costPenalty: 2, term: g.newTermSequence({
				symbolName: g.hyphenate(prepSymNamePrefix, 'over', 'substituted', 'prepositions'),
				acceptedTerms: [ 'aboard', 'absent', 'across', 'afore', 'after', 'against', 'along', 'alongside', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'athwart', 'atop', 'barring', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'between', 'betwixt', 'but', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'given', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'next', 'notwithstanding', 'off', 'onto', 'opposite', 'out', 'outside', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'via', 'with', 'within', 'without', 'worth' ],
		}) },
	],
})

// (issues with) under (`<int>` comments)
exports.under = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'under'),
	insertionCost: 0.5,
	acceptedTerms: [
		'under',
		'below',
		'<',
		[ terms.fewer, exports.than ],
	],
	substitutedTerms: [
		{ costPenalty: 2, term: g.newTermSequence({
				symbolName: g.hyphenate(prepSymNamePrefix, 'under', 'substituted', 'prepositions'),
				acceptedTerms: [ 'aboard', 'above', 'absent', 'across', 'afore', 'after', 'against', 'along', 'alongside', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'athwart', 'atop', 'barring', 'before', 'behind', 'beneath', 'beside', 'besides', 'between', 'betwixt', 'beyond', 'but', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'given', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'next', 'notwithstanding', 'off', 'onto', 'opposite', 'out', 'outside', 'over', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'toward', 'towards', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'via', 'with', 'within', 'without', 'worth' ],
		}) },
	],
})

// (companies that raised `<int>`) in (funding)
exports.medium = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'medium'),
	insertionCost: 0.5,
	acceptedTerms: [ 'in', 'of' ],
})

// The benefactive case expresses the person/thing (i.e., the referent of the noun) that benefits from the action of the verb (or the situation expressed by the clause). E.g., "for", "for the benefit of", and "intended for".
// (people who work) at|for (`[company]`)
exports.benefactive = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'benefactive'),
	insertionCost: 0.5,
	acceptedTerms: [ 'at', 'for' ],
	substitutedTerms: [
		{ costPenalty: 3, term: g.newTermSequence({
				symbolName: g.hyphenate(prepSymNamePrefix, 'benefactive', 'substituted', 'prepositions'),
				acceptedTerms: [ 'aboard', 'above', 'absent', 'across', 'afore', 'after', 'against', 'along', 'alongside', 'amid', 'amidst', 'among', 'amongst', 'around', 'aside', 'astride', 'athwart', 'atop', 'barring', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'between', 'betwixt', 'beyond', 'but', 'despite', 'down', 'during', 'except', 'excluding', 'failing', 'following', 'from', 'given', 'including', 'inside', 'into', 'lest', 'like', 'minus', 'modulo', 'near', 'next', 'notwithstanding', 'off', 'onto', 'opposite', 'out', 'outside', 'over', 'pace', 'past', 'per', 'plus', 'pro', 'qua', 'sans', 'save', 'since', 'than', 'through', 'thru', 'throughout', 'thruout', 'till', 'times', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus', 'vs', 'via', 'with', 'within', 'without', 'worth' ],
		}) },
	],
})

// (followers I and `{user}` have) in (common)
// (followers I have) in (common with `{user}`)
// (companies `[nom-users+]` invested) in
exports.in = g.newTermSequence({
	symbolName: g.hyphenate(prepSymNamePrefix, 'in'),
	insertionCost: 0.5,
	acceptedTerms: [ 'in' ],
})