/**
 * Each term can be deleted when recognized in input, and each term is only 1 token in length. A sequence of multiple tokens can also be deleted.
 *
 * For the token(s) that immediately follow the deletable tokens, nodes are created for each terminal rule to the token as normal, as well as a second set of nodes for the same terminal rules with a larger `size` value for the larger token span and a cost penalty of 1 per deleted token.
 */

module.exports = [
	'a',
	'again',
	'all',
	'also',
	'am',
	'an',
	'and',
	'any',
	'are',
	'as',
	'because',
	'both',
	'but',
	'cannot',
	'did',
	'do',
	'does',
	'doing',
	'for',
	'here',
	'how',
	'is',
	'it',
	'just',
	'more',
	'most',
	'nor',
	'not',
	'once',
	'only',
	'or',
	'some',
	'the',
	'there',
	'these',
	'those',
	'too',
	'until',
	'while',
	'why',
]